version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000-9000:8000"
    volumes:
      - ./backend:/app
    command: ["python", "app/main.py"]
    environment:
      - APP_ENVIRONMENT=docker
  frontend:
    build: ./frontend
    ports:
      - "3000-4000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    environment:
      - APP_ENVIRONMENT=docker
