version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["python", "app/main.py"]
    environment:
      - APP_ENVIRONMENT=docker
      - GROQ_API_KEY=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
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    environment:
      - APP_ENVIRONMENT=docker
